# Generated by Django 3.0.5 on 2021-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('units', models.CharField(choices=[('кг.', 'киллограм'), ('гр.', 'грамм'), ('л.', 'литр'), ('мл.', 'миллилитр'), ('ст.', 'стакан'), ('ч.л.', 'чайная ложка'), ('стл.л.', 'столовая ложка')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images')),
                ('text', models.CharField(max_length=1000, verbose_name='Описание')),
                ('time_to_cook', models.IntegerField(verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(choices=[('#34568B', 'Blue'), ('#FF6F61', 'Coral'), ('#6B5B95', 'Violet'), ('#88B04B', 'Green')], max_length=100)),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
            ],
        ),
    ]
