# Generated by Django 3.0.5 on 2021-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211107_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='cart',
            field=models.ManyToManyField(blank=True, to='products.Recipe'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
