# Generated by Django 3.0.5 on 2021-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211113_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favoriterecipes',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='products.Recipe'),
        ),
    ]
